2020-10-01 10:50:51,015 (1095/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-10-01 10:50:51,140 (1095/MainThread) pgcli.pgstyle ERROR - Unhandled style / class name: literal.string
2020-10-01 10:50:51,140 (1095/MainThread) pgcli.pgstyle ERROR - Unhandled style / class name: literal.number
2020-10-01 10:50:51,140 (1095/MainThread) pgcli.pgstyle ERROR - Unhandled style / class name: keyword
2020-10-01 10:50:51,140 (1095/MainThread) pgcli.pgstyle ERROR - Unhandled style / class name: output.null
2020-10-01 10:50:51,194 (1095/MainThread) pgcli.pgstyle ERROR - Unhandled style / class name: Token.Prompt
2020-10-01 10:52:02,908 (1164/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-10-01 10:52:02,957 (1164/MainThread) pgcli.pgstyle ERROR - Unhandled style / class name: literal.string
2020-10-01 10:52:02,957 (1164/MainThread) pgcli.pgstyle ERROR - Unhandled style / class name: literal.number
2020-10-01 10:52:02,957 (1164/MainThread) pgcli.pgstyle ERROR - Unhandled style / class name: keyword
2020-10-01 10:52:02,957 (1164/MainThread) pgcli.pgstyle ERROR - Unhandled style / class name: output.null
2020-10-01 10:52:02,991 (1164/MainThread) pgcli.pgstyle ERROR - Unhandled style / class name: Token.Prompt
2020-10-01 10:52:20,472 (1164/MainThread) pgcli.pgexecute ERROR - sql: 'show table', error: SyntaxError('syntax error at or near "table"\nLINE 1: show table\n             ^\n')
2020-10-01 10:52:20,473 (1164/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "table"\nLINE 1: show table\n             ^\n\n'
2020-10-01 10:52:27,119 (1164/MainThread) pgcli.pgexecute ERROR - sql: 'show database', error: UndefinedObject('unrecognized configuration parameter "database"\n')
2020-10-01 10:52:27,119 (1164/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedObject: unrecognized configuration parameter "database"\n\n'
2020-10-01 10:52:27,999 (1164/MainThread) pgcli.pgexecute ERROR - sql: 'show databases', error: UndefinedObject('unrecognized configuration parameter "databases"\n')
2020-10-01 10:52:27,999 (1164/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedObject: unrecognized configuration parameter "databases"\n\n'
2020-10-01 10:52:33,695 (1164/MainThread) pgcli.pgexecute ERROR - sql: 'show DATABASE', error: UndefinedObject('unrecognized configuration parameter "database"\n')
2020-10-01 10:52:33,695 (1164/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedObject: unrecognized configuration parameter "database"\n\n'
2020-10-01 10:52:38,305 (1164/MainThread) pgcli.pgexecute ERROR - sql: 'show /?', error: SyntaxError('syntax error at or near "/?"\nLINE 1: show /?\n             ^\n')
2020-10-01 10:52:38,305 (1164/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "/?"\nLINE 1: show /?\n             ^\n\n'
2020-10-01 10:52:39,868 (1164/MainThread) pgcli.pgexecute ERROR - sql: 'show', error: SyntaxError('syntax error at end of input\nLINE 1: show\n            ^\n')
2020-10-01 10:52:39,868 (1164/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at end of input\nLINE 1: show\n            ^\n\n'
2020-10-01 10:52:44,876 (1164/MainThread) pgcli.pgexecute ERROR - sql: 'show FROM', error: SyntaxError('syntax error at or near "FROM"\nLINE 1: show FROM\n             ^\n')
2020-10-01 10:52:44,876 (1164/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "FROM"\nLINE 1: show FROM\n             ^\n\n'
2020-10-01 10:52:55,252 (1164/MainThread) pgcli.pgexecute ERROR - sql: 'show TABLE', error: SyntaxError('syntax error at or near "TABLE"\nLINE 1: show TABLE\n             ^\n')
2020-10-01 10:52:55,252 (1164/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "TABLE"\nLINE 1: show TABLE\n             ^\n\n'
2020-10-01 10:52:56,532 (1164/MainThread) pgcli.pgexecute ERROR - sql: 'show TABLEs', error: UndefinedObject('unrecognized configuration parameter "tables"\n')
2020-10-01 10:52:56,532 (1164/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedObject: unrecognized configuration parameter "tables"\n\n'
2020-10-01 10:53:00,561 (1164/MainThread) pgcli.pgexecute ERROR - sql: 'ks', error: SyntaxError('syntax error at or near "ks"\nLINE 1: ks\n        ^\n')
2020-10-01 10:53:00,561 (1164/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "ks"\nLINE 1: ks\n        ^\n\n'
2020-10-01 10:54:02,159 (1188/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-10-01 10:54:02,208 (1188/MainThread) pgcli.pgstyle ERROR - Unhandled style / class name: literal.string
2020-10-01 10:54:02,208 (1188/MainThread) pgcli.pgstyle ERROR - Unhandled style / class name: literal.number
2020-10-01 10:54:02,208 (1188/MainThread) pgcli.pgstyle ERROR - Unhandled style / class name: keyword
2020-10-01 10:54:02,208 (1188/MainThread) pgcli.pgstyle ERROR - Unhandled style / class name: output.null
2020-10-01 10:54:02,241 (1188/MainThread) pgcli.pgstyle ERROR - Unhandled style / class name: Token.Prompt
2020-10-01 10:54:04,949 (1188/MainThread) pgcli.pgexecute ERROR - sql: 'show database', error: UndefinedObject('unrecognized configuration parameter "database"\n')
2020-10-01 10:54:04,949 (1188/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedObject: unrecognized configuration parameter "database"\n\n'
2020-10-01 10:54:05,605 (1188/MainThread) pgcli.pgexecute ERROR - sql: 'ls', error: SyntaxError('syntax error at or near "ls"\nLINE 1: ls\n        ^\n')
2020-10-01 10:54:05,606 (1188/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "ls"\nLINE 1: ls\n        ^\n\n'
2020-10-01 10:54:05,932 (1188/MainThread) pgcli.pgexecute ERROR - sql: 'ls', error: SyntaxError('syntax error at or near "ls"\nLINE 1: ls\n        ^\n')
2020-10-01 10:54:05,933 (1188/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "ls"\nLINE 1: ls\n        ^\n\n'
2020-10-01 10:54:31,496 (1211/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-10-01 10:54:31,545 (1211/MainThread) pgcli.pgstyle ERROR - Unhandled style / class name: literal.string
2020-10-01 10:54:31,545 (1211/MainThread) pgcli.pgstyle ERROR - Unhandled style / class name: literal.number
2020-10-01 10:54:31,545 (1211/MainThread) pgcli.pgstyle ERROR - Unhandled style / class name: keyword
2020-10-01 10:54:31,546 (1211/MainThread) pgcli.pgstyle ERROR - Unhandled style / class name: output.null
2020-10-01 10:54:31,578 (1211/MainThread) pgcli.pgstyle ERROR - Unhandled style / class name: Token.Prompt
2020-10-01 10:54:33,563 (1211/MainThread) pgcli.pgexecute ERROR - sql: 'show database', error: UndefinedObject('unrecognized configuration parameter "database"\n')
2020-10-01 10:54:33,564 (1211/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedObject: unrecognized configuration parameter "database"\n\n'
2020-10-01 10:54:35,354 (1211/MainThread) pgcli.pgexecute ERROR - sql: 'llllds', error: SyntaxError('syntax error at or near "llllds"\nLINE 1: llllds\n        ^\n')
2020-10-01 10:54:35,354 (1211/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "llllds"\nLINE 1: llllds\n        ^\n\n'
2020-10-01 10:54:35,878 (1211/MainThread) pgcli.pgexecute ERROR - sql: 'fasd', error: SyntaxError('syntax error at or near "fasd"\nLINE 1: fasd\n        ^\n')
2020-10-01 10:54:35,879 (1211/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "fasd"\nLINE 1: fasd\n        ^\n\n'
2020-10-01 10:54:53,981 (1251/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-10-01 10:54:54,030 (1251/MainThread) pgcli.pgstyle ERROR - Unhandled style / class name: literal.string
2020-10-01 10:54:54,030 (1251/MainThread) pgcli.pgstyle ERROR - Unhandled style / class name: literal.number
2020-10-01 10:54:54,030 (1251/MainThread) pgcli.pgstyle ERROR - Unhandled style / class name: keyword
2020-10-01 10:54:54,030 (1251/MainThread) pgcli.pgstyle ERROR - Unhandled style / class name: output.null
2020-10-01 10:54:54,063 (1251/MainThread) pgcli.pgstyle ERROR - Unhandled style / class name: Token.Prompt
2020-10-01 10:54:56,492 (1251/MainThread) pgcli.pgexecute ERROR - sql: 'show database', error: UndefinedObject('unrecognized configuration parameter "database"\n')
2020-10-01 10:54:56,492 (1251/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedObject: unrecognized configuration parameter "database"\n\n'
2020-10-03 01:11:33,048 (5015/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-10-03 01:11:33,133 (5015/MainThread) pgcli.pgstyle ERROR - Unhandled style / class name: literal.string
2020-10-03 01:11:33,133 (5015/MainThread) pgcli.pgstyle ERROR - Unhandled style / class name: literal.number
2020-10-03 01:11:33,133 (5015/MainThread) pgcli.pgstyle ERROR - Unhandled style / class name: keyword
2020-10-03 01:11:33,133 (5015/MainThread) pgcli.pgstyle ERROR - Unhandled style / class name: output.null
2020-10-03 01:11:33,205 (5015/MainThread) pgcli.pgstyle ERROR - Unhandled style / class name: Token.Prompt
2020-10-03 01:11:36,200 (5015/MainThread) pgcli.pgexecute ERROR - sql: 'show database', error: UndefinedObject('unrecognized configuration parameter "database"\n')
2020-10-03 01:11:36,209 (5015/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedObject: unrecognized configuration parameter "database"\n\n'
2020-10-03 01:11:45,458 (5131/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-10-03 01:11:45,506 (5131/MainThread) pgcli.pgstyle ERROR - Unhandled style / class name: literal.string
2020-10-03 01:11:45,506 (5131/MainThread) pgcli.pgstyle ERROR - Unhandled style / class name: literal.number
2020-10-03 01:11:45,506 (5131/MainThread) pgcli.pgstyle ERROR - Unhandled style / class name: keyword
2020-10-03 01:11:45,506 (5131/MainThread) pgcli.pgstyle ERROR - Unhandled style / class name: output.null
2020-10-03 01:11:45,538 (5131/MainThread) pgcli.pgstyle ERROR - Unhandled style / class name: Token.Prompt
2020-10-03 01:11:47,770 (5131/MainThread) pgcli.pgexecute ERROR - sql: 'show database', error: UndefinedObject('unrecognized configuration parameter "database"\n')
2020-10-03 01:11:47,770 (5131/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedObject: unrecognized configuration parameter "database"\n\n'
2020-10-04 11:45:57,096 (2233/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-10-04 11:45:57,262 (2233/MainThread) pgcli.pgstyle ERROR - Unhandled style / class name: literal.string
2020-10-04 11:45:57,262 (2233/MainThread) pgcli.pgstyle ERROR - Unhandled style / class name: literal.number
2020-10-04 11:45:57,262 (2233/MainThread) pgcli.pgstyle ERROR - Unhandled style / class name: keyword
2020-10-04 11:45:57,262 (2233/MainThread) pgcli.pgstyle ERROR - Unhandled style / class name: output.null
2020-10-04 11:45:57,358 (2233/MainThread) pgcli.pgstyle ERROR - Unhandled style / class name: Token.Prompt
2020-10-04 11:46:02,504 (2233/MainThread) pgcli.pgexecute ERROR - sql: 'show database', error: UndefinedObject('unrecognized configuration parameter "database"\n')
2020-10-04 11:46:02,514 (2233/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedObject: unrecognized configuration parameter "database"\n\n'
2020-10-04 11:47:52,046 (2412/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-10-04 11:47:52,131 (2412/MainThread) pgcli.pgstyle ERROR - Unhandled style / class name: literal.string
2020-10-04 11:47:52,131 (2412/MainThread) pgcli.pgstyle ERROR - Unhandled style / class name: literal.number
2020-10-04 11:47:52,131 (2412/MainThread) pgcli.pgstyle ERROR - Unhandled style / class name: keyword
2020-10-04 11:47:52,132 (2412/MainThread) pgcli.pgstyle ERROR - Unhandled style / class name: output.null
2020-10-04 11:47:52,204 (2412/MainThread) pgcli.pgstyle ERROR - Unhandled style / class name: Token.Prompt
2020-10-04 11:47:54,469 (2412/MainThread) pgcli.pgexecute ERROR - sql: 'show database', error: UndefinedObject('unrecognized configuration parameter "database"\n')
2020-10-04 11:47:54,469 (2412/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedObject: unrecognized configuration parameter "database"\n\n'
2020-10-04 11:48:01,781 (2412/MainThread) pgcli.pgexecute ERROR - sql: 'show DATABASE', error: UndefinedObject('unrecognized configuration parameter "database"\n')
2020-10-04 11:48:01,781 (2412/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedObject: unrecognized configuration parameter "database"\n\n'
2020-10-04 11:48:04,113 (2412/MainThread) pgcli.pgexecute ERROR - sql: 'help', error: SyntaxError('syntax error at or near "help"\nLINE 1: help\n        ^\n')
2020-10-04 11:48:04,113 (2412/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "help"\nLINE 1: help\n        ^\n\n'
2020-10-04 11:56:50,777 (2885/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-10-04 11:56:50,855 (2885/MainThread) pgcli.pgstyle ERROR - Unhandled style / class name: literal.string
2020-10-04 11:56:50,855 (2885/MainThread) pgcli.pgstyle ERROR - Unhandled style / class name: literal.number
2020-10-04 11:56:50,855 (2885/MainThread) pgcli.pgstyle ERROR - Unhandled style / class name: keyword
2020-10-04 11:56:50,855 (2885/MainThread) pgcli.pgstyle ERROR - Unhandled style / class name: output.null
2020-10-04 11:56:50,911 (2885/MainThread) pgcli.pgstyle ERROR - Unhandled style / class name: Token.Prompt
2020-10-15 08:21:13,702 (5191/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-10-15 08:21:14,207 (5191/MainThread) pgcli.pgstyle ERROR - Unhandled style / class name: Token.Prompt
2020-10-15 08:21:17,647 (5191/MainThread) pgcli.pgexecute ERROR - sql: 'show table', error: SyntaxError('syntax error at or near "table"\nLINE 1: show table\n             ^\n')
2020-10-15 08:21:17,648 (5191/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "table"\nLINE 1: show table\n             ^\n\n'
2020-10-15 08:23:48,442 (5283/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-10-15 08:23:48,668 (5283/MainThread) pgcli.pgstyle ERROR - Unhandled style / class name: Token.Prompt
2020-10-15 08:23:51,031 (5283/MainThread) pgcli.pgexecute ERROR - sql: 'show table', error: SyntaxError('syntax error at or near "table"\nLINE 1: show table\n             ^\n')
2020-10-15 08:23:51,032 (5283/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "table"\nLINE 1: show table\n             ^\n\n'
2020-10-15 08:29:15,296 (5333/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-10-15 08:29:15,463 (5333/MainThread) pgcli.pgstyle ERROR - Unhandled style / class name: Token.Prompt
2020-10-15 08:29:55,049 (5372/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-10-15 08:29:55,211 (5372/MainThread) pgcli.pgstyle ERROR - Unhandled style / class name: Token.Prompt
2020-10-15 08:29:59,077 (5372/MainThread) pgcli.pgexecute ERROR - sql: 'show table', error: SyntaxError('syntax error at or near "table"\nLINE 1: show table\n             ^\n')
2020-10-15 08:29:59,077 (5372/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "table"\nLINE 1: show table\n             ^\n\n'
2020-10-15 08:30:01,722 (5372/MainThread) pgcli.pgexecute ERROR - sql: 'help', error: SyntaxError('syntax error at or near "help"\nLINE 1: help\n        ^\n')
2020-10-15 08:30:01,722 (5372/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "help"\nLINE 1: help\n        ^\n\n'
2020-10-15 08:30:04,939 (5372/MainThread) pgcli.pgexecute ERROR - sql: '.help', error: SyntaxError('syntax error at or near "."\nLINE 1: .help\n        ^\n')
2020-10-15 08:30:04,940 (5372/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "."\nLINE 1: .help\n        ^\n\n'
2020-10-15 08:30:06,316 (5372/MainThread) pgcli.pgexecute ERROR - sql: '\\help', error: SyntaxError('syntax error at or near "\\"\nLINE 1: \\help\n        ^\n')
2020-10-15 08:30:06,316 (5372/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "\\"\nLINE 1: \\help\n        ^\n\n'
2020-10-15 08:30:44,717 (5372/MainThread) pgcli.pgexecute ERROR - sql: '7h', error: SyntaxError('syntax error at or near "7"\nLINE 1: 7h\n        ^\n')
2020-10-15 08:30:44,718 (5372/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "7"\nLINE 1: 7h\n        ^\n\n'
2020-10-15 08:31:15,828 (5372/MainThread) pgcli.pgexecute ERROR - sql: 'show table', error: SyntaxError('syntax error at or near "table"\nLINE 1: show table\n             ^\n')
2020-10-15 08:31:15,828 (5372/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "table"\nLINE 1: show table\n             ^\n\n'
2020-10-15 08:31:16,659 (5372/MainThread) pgcli.pgexecute ERROR - sql: 'show tables', error: UndefinedObject('unrecognized configuration parameter "tables"\n')
2020-10-15 08:31:16,659 (5372/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedObject: unrecognized configuration parameter "tables"\n\n'
2020-10-15 08:31:29,028 (5372/MainThread) pgcli.pgexecute ERROR - sql: 'show name', error: UndefinedObject('unrecognized configuration parameter "name"\n')
2020-10-15 08:31:29,028 (5372/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedObject: unrecognized configuration parameter "name"\n\n'
2020-10-15 08:37:28,782 (5372/MainThread) pgcli.pgexecute ERROR - sql: 'select table_name from information_schema..tables', error: SyntaxError('syntax error at or near ".."\nLINE 1: select table_name from information_schema..tables\n                                                 ^\n')
2020-10-15 08:37:28,782 (5372/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near ".."\nLINE 1: select table_name from information_schema..tables\n                                                 ^\n\n'
2020-10-15 08:37:47,079 (5372/MainThread) pgcli.pgexecute ERROR - sql: "select table_name from information_schema..tables where table_schema='public'", error: SyntaxError('syntax error at or near ".."\nLINE 1: select table_name from information_schema..tables where tabl...\n                                                 ^\n')
2020-10-15 08:37:47,079 (5372/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near ".."\nLINE 1: select table_name from information_schema..tables where tabl...\n                                                 ^\n\n'
2020-10-15 08:39:19,622 (5447/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-10-15 08:39:19,771 (5447/MainThread) pgcli.pgstyle ERROR - Unhandled style / class name: Token.Prompt
2020-10-15 09:29:04,034 (5792/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-10-15 09:29:04,180 (5792/MainThread) pgcli.pgstyle ERROR - Unhandled style / class name: Token.Prompt
2020-10-15 09:32:21,689 (5792/MainThread) pgcli.pgexecute ERROR - sql: 'select DATE()', error: UndefinedFunction('function date() does not exist\nLINE 1: select DATE()\n               ^\nHINT:  No function matches the given name and argument types. You might need to add explicit type casts.\n')
2020-10-15 09:32:21,689 (5792/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedFunction: function date() does not exist\nLINE 1: select DATE()\n               ^\nHINT:  No function matches the given name and argument types. You might need to add explicit type casts.\n\n'
2020-10-15 09:32:28,605 (5792/MainThread) pgcli.pgexecute ERROR - sql: 'select DATE(CTRDATE())', error: UndefinedFunction('function ctrdate() does not exist\nLINE 1: select DATE(CTRDATE())\n                    ^\nHINT:  No function matches the given name and argument types. You might need to add explicit type casts.\n')
2020-10-15 09:32:28,605 (5792/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedFunction: function ctrdate() does not exist\nLINE 1: select DATE(CTRDATE())\n                    ^\nHINT:  No function matches the given name and argument types. You might need to add explicit type casts.\n\n'
2020-10-15 09:32:33,872 (5792/MainThread) pgcli.pgexecute ERROR - sql: 'select YEAR()', error: UndefinedFunction('function year() does not exist\nLINE 1: select YEAR()\n               ^\nHINT:  No function matches the given name and argument types. You might need to add explicit type casts.\n')
2020-10-15 09:32:33,873 (5792/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedFunction: function year() does not exist\nLINE 1: select YEAR()\n               ^\nHINT:  No function matches the given name and argument types. You might need to add explicit type casts.\n\n'
2020-10-15 09:32:35,374 (5792/MainThread) pgcli.pgexecute ERROR - sql: 'select YEAR', error: UndefinedColumn('column "year" does not exist\nLINE 1: select YEAR\n               ^\n')
2020-10-15 09:32:35,374 (5792/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedColumn: column "year" does not exist\nLINE 1: select YEAR\n               ^\n\n'
2020-10-15 09:32:50,666 (5792/MainThread) pgcli.pgexecute ERROR - sql: 'select YEAR(CURDATE()', error: SyntaxError('syntax error at end of input\nLINE 1: select YEAR(CURDATE()\n                             ^\n')
2020-10-15 09:32:50,667 (5792/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at end of input\nLINE 1: select YEAR(CURDATE()\n                             ^\n\n'
2020-10-15 09:32:52,439 (5792/MainThread) pgcli.pgexecute ERROR - sql: 'select YEAR(CURDATE())', error: UndefinedFunction('function curdate() does not exist\nLINE 1: select YEAR(CURDATE())\n                    ^\nHINT:  No function matches the given name and argument types. You might need to add explicit type casts.\n')
2020-10-15 09:32:52,439 (5792/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedFunction: function curdate() does not exist\nLINE 1: select YEAR(CURDATE())\n                    ^\nHINT:  No function matches the given name and argument types. You might need to add explicit type casts.\n\n'
2020-10-15 09:33:45,853 (5792/MainThread) pgcli.pgexecute ERROR - sql: 'select CURRENT_DATE()', error: SyntaxError('syntax error at or near "("\nLINE 1: select CURRENT_DATE()\n                           ^\n')
2020-10-15 09:33:45,853 (5792/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "("\nLINE 1: select CURRENT_DATE()\n                           ^\n\n'
2020-10-15 09:33:58,502 (5792/MainThread) pgcli.pgexecute ERROR - sql: 'select e', error: UndefinedColumn('column "e" does not exist\nLINE 1: select e\n               ^\n')
2020-10-15 09:33:58,502 (5792/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedColumn: column "e" does not exist\nLINE 1: select e\n               ^\n\n'
2020-10-15 09:34:00,221 (5792/MainThread) pgcli.pgexecute ERROR - sql: 'select PI', error: UndefinedColumn('column "pi" does not exist\nLINE 1: select PI\n               ^\n')
2020-10-15 09:34:00,221 (5792/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedColumn: column "pi" does not exist\nLINE 1: select PI\n               ^\n\n'
2020-10-15 09:34:08,156 (5792/MainThread) pgcli.pgexecute ERROR - sql: 'select MAX', error: UndefinedColumn('column "max" does not exist\nLINE 1: select MAX\n               ^\n')
2020-10-15 09:34:08,156 (5792/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedColumn: column "max" does not exist\nLINE 1: select MAX\n               ^\n\n'
2020-10-15 09:35:04,397 (5792/MainThread) pgcli.pgexecute ERROR - sql: 'insert into test (name) values ("Arthur")', error: UndefinedColumn('column "Arthur" does not exist\nLINE 1: insert into test (name) values ("Arthur")\n                                        ^\n')
2020-10-15 09:35:04,397 (5792/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedColumn: column "Arthur" does not exist\nLINE 1: insert into test (name) values ("Arthur")\n                                        ^\n\n'
2020-10-15 09:35:58,628 (5792/MainThread) pgcli.pgexecute ERROR - sql: 'alter table test\nadd birthday', error: SyntaxError('syntax error at end of input\nLINE 2: add birthday\n                    ^\n')
2020-10-15 09:35:58,628 (5792/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at end of input\nLINE 2: add birthday\n                    ^\n\n'
2020-10-15 09:38:35,151 (5792/MainThread) pgcli.pgexecute ERROR - sql: 'alter table test\nalter column name varchar(255)\n', error: SyntaxError('syntax error at or near "varchar"\nLINE 2: alter column name varchar(255)\n                          ^\n')
2020-10-15 09:38:35,151 (5792/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "varchar"\nLINE 2: alter column name varchar(255)\n                          ^\n\n'
2020-10-15 09:52:48,020 (5792/MainThread) pgcli.pgexecute ERROR - sql: "insert into customers (firstname, lastname, ciry)\nvalues (\n('John', 'Smith', 'New York'),\n('David', 'Williams', 'Los Angeles'),\n('Chloe', 'Anderson', 'Chicago'),\n('Emily', 'Adams', 'Houston'),\n('James', 'Roberts', 'Mars'),\n('MeMyself', 'Oops', 'my hourse')\n)", error: SyntaxError("INSERT has more expressions than target columns\nLINE 6: ('Emily', 'Adams', 'Houston'),\n        ^\n")
2020-10-15 09:52:48,021 (5792/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: INSERT has more expressions than target columns\nLINE 6: (\'Emily\', \'Adams\', \'Houston\'),\n        ^\n\n'
2020-10-21 01:26:57,463 (72167/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-10-21 01:26:57,552 (72167/MainThread) pgcli.pgstyle ERROR - Unhandled style / class name: Token.Prompt
2020-10-21 10:17:51,761 (5999/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-10-21 10:17:51,904 (5999/MainThread) pgcli.pgstyle ERROR - Unhandled style / class name: Token.Prompt
2020-10-21 10:20:04,627 (13181/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-10-21 10:20:04,772 (13181/MainThread) pgcli.pgstyle ERROR - Unhandled style / class name: Token.Prompt
2020-10-23 10:37:16,713 (27318/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-10-23 10:37:16,917 (27318/MainThread) pgcli.pgstyle ERROR - Unhandled style / class name: Token.Prompt
2020-11-12 09:46:56,003 (15330/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-11-12 09:46:56,181 (15330/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/main.py", line 562, in connect\n    raise e\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/main.py", line 549, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/home/arthur/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: could not connect to server: No such file or directory\n\tIs the server running locally and accepting\n\tconnections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?\n\n'
2020-11-12 09:48:00,168 (15405/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-11-12 09:48:00,336 (15405/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/main.py", line 562, in connect\n    raise e\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/main.py", line 549, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/home/arthur/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: could not connect to server: No such file or directory\n\tIs the server running locally and accepting\n\tconnections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?\n\n'
2020-11-12 09:56:43,877 (18668/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-11-12 09:56:44,066 (18668/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/main.py", line 562, in connect\n    raise e\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/main.py", line 549, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/home/arthur/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: could not connect to server: No such file or directory\n\tIs the server running locally and accepting\n\tconnections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?\n\n'
2020-11-12 09:58:40,892 (18860/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-11-12 09:58:41,069 (18860/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/main.py", line 562, in connect\n    raise e\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/main.py", line 549, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/home/arthur/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: could not connect to server: No such file or directory\n\tIs the server running locally and accepting\n\tconnections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?\n\n'
2020-11-12 10:15:11,769 (6254/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-11-12 10:15:12,012 (6254/MainThread) pgcli.pgstyle ERROR - Unhandled style / class name: Token.Prompt
2020-11-12 10:34:10,865 (7531/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-11-12 10:34:10,968 (7531/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/main.py", line 562, in connect\n    raise e\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/main.py", line 549, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/home/arthur/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: could not connect to server: No such file or directory\n\tIs the server running locally and accepting\n\tconnections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?\n\n'
2020-11-12 10:34:19,997 (7587/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-11-12 10:34:20,130 (7587/MainThread) pgcli.pgstyle ERROR - Unhandled style / class name: Token.Prompt
2020-12-25 10:36:54,158 (3032/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-12-25 10:36:54,253 (3032/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/main.py", line 562, in connect\n    raise e\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/main.py", line 549, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/lib/python3/dist-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: could not connect to server: No such file or directory\n\tIs the server running locally and accepting\n\tconnections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?\n\n'
2020-12-25 10:37:14,595 (3173/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-12-25 10:37:14,729 (3173/MainThread) pgcli.pgstyle ERROR - Unhandled style / class name: Token.Prompt
2020-12-25 10:37:30,692 (3173/MainThread) pgcli.pgexecute ERROR - sql: '.help', error: SyntaxError('syntax error at or near "."\nLINE 1: .help\n        ^\n')
2020-12-25 10:37:30,692 (3173/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "."\nLINE 1: .help\n        ^\n\n'
2020-12-25 10:37:34,286 (3173/MainThread) pgcli.pgexecute ERROR - sql: '/help', error: SyntaxError('syntax error at or near "/"\nLINE 1: /help\n        ^\n')
2020-12-25 10:37:34,286 (3173/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "/"\nLINE 1: /help\n        ^\n\n'
2020-12-25 10:37:36,350 (3173/MainThread) pgcli.pgexecute ERROR - sql: '\\help', error: SyntaxError('syntax error at or near "\\"\nLINE 1: \\help\n        ^\n')
2020-12-25 10:37:36,351 (3173/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "\\"\nLINE 1: \\help\n        ^\n\n'
2020-12-25 10:37:41,003 (3173/MainThread) pgcli.pgexecute ERROR - sql: '.use', error: SyntaxError('syntax error at or near "."\nLINE 1: .use\n        ^\n')
2020-12-25 10:37:41,003 (3173/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "."\nLINE 1: .use\n        ^\n\n'
2020-12-25 10:37:44,225 (3173/MainThread) pgcli.pgexecute ERROR - sql: '/use', error: SyntaxError('syntax error at or near "/"\nLINE 1: /use\n        ^\n')
2020-12-25 10:37:44,226 (3173/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "/"\nLINE 1: /use\n        ^\n\n'
2020-12-25 10:37:45,321 (3173/MainThread) pgcli.pgexecute ERROR - sql: '/?', error: SyntaxError('syntax error at or near "/?"\nLINE 1: /?\n        ^\n')
2020-12-25 10:37:45,322 (3173/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "/?"\nLINE 1: /?\n        ^\n\n'
2020-12-25 10:37:46,346 (3173/MainThread) pgcli.pgexecute ERROR - sql: '?', error: SyntaxError('syntax error at or near "?"\nLINE 1: ?\n        ^\n')
2020-12-25 10:37:46,347 (3173/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "?"\nLINE 1: ?\n        ^\n\n'
2020-12-25 10:37:47,505 (3173/MainThread) pgcli.pgexecute ERROR - sql: '.?', error: SyntaxError('syntax error at or near "."\nLINE 1: .?\n        ^\n')
2020-12-25 10:37:47,505 (3173/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "."\nLINE 1: .?\n        ^\n\n'
2020-12-25 10:40:02,252 (3173/MainThread) pgcli.pgexecute ERROR - sql: 'select \\?', error: SyntaxError('syntax error at or near "\\"\nLINE 1: select \\?\n               ^\n')
2020-12-25 10:40:02,252 (3173/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "\\"\nLINE 1: select \\?\n               ^\n\n'
2020-12-25 10:40:13,507 (3173/MainThread) pgcli.pgexecute ERROR - sql: 'select 8 as 10', error: SyntaxError('syntax error at or near "10"\nLINE 1: select 8 as 10\n                    ^\n')
2020-12-25 10:40:13,507 (3173/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "10"\nLINE 1: select 8 as 10\n                    ^\n\n'
2020-12-25 10:40:22,752 (3173/MainThread) pgcli.pgexecute ERROR - sql: "select 8 as '10'", error: SyntaxError('syntax error at or near "\'10\'"\nLINE 1: select 8 as \'10\'\n                    ^\n')
2020-12-25 10:40:22,752 (3173/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/arthur/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "\'10\'"\nLINE 1: select 8 as \'10\'\n                    ^\n\n'
2021-02-01 13:59:36,431 (109080/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2021-02-01 13:59:36,561 (109080/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/arthur/.local/lib/python3.9/site-packages/pgcli/main.py", line 582, in connect\n    raise e\n  File "/home/arthur/.local/lib/python3.9/site-packages/pgcli/main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/home/arthur/.local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/home/arthur/.local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/lib/python3/dist-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: could not connect to server: No such file or directory\n\tIs the server running locally and accepting\n\tconnections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?\n\n'
2021-07-05 15:53:47,955 (200939/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2021-07-05 15:54:28,483 (201044/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2021-07-05 15:56:30,689 (201606/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2021-07-05 16:13:12,161 (205916/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2021-07-05 16:13:15,183 (205916/MainThread) pgcli.pgexecute ERROR - sql: 'show database', error: UndefinedObject('unrecognized configuration parameter "database"\n')
2021-07-05 16:13:15,183 (205916/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/arthur/.local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/arthur/.local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedObject: unrecognized configuration parameter "database"\n\n'
2021-07-05 16:13:17,130 (205916/MainThread) pgcli.pgexecute ERROR - sql: '.database', error: SyntaxError('syntax error at or near "."\nLINE 1: .database\n        ^\n')
2021-07-05 16:13:17,130 (205916/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/arthur/.local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/arthur/.local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "."\nLINE 1: .database\n        ^\n\n'
2021-07-05 16:13:18,453 (205916/MainThread) pgcli.pgexecute ERROR - sql: '.databases', error: SyntaxError('syntax error at or near "."\nLINE 1: .databases\n        ^\n')
2021-07-05 16:13:18,453 (205916/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/arthur/.local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/arthur/.local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "."\nLINE 1: .databases\n        ^\n\n'
2021-07-05 16:13:20,401 (205916/MainThread) pgcli.pgexecute ERROR - sql: '/?', error: SyntaxError('syntax error at or near "/?"\nLINE 1: /?\n        ^\n')
2021-07-05 16:13:20,402 (205916/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/arthur/.local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/arthur/.local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "/?"\nLINE 1: /?\n        ^\n\n'
2021-07-05 16:13:21,751 (205916/MainThread) pgcli.pgexecute ERROR - sql: '?', error: SyntaxError('syntax error at or near "?"\nLINE 1: ?\n        ^\n')
2021-07-05 16:13:21,752 (205916/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/arthur/.local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/arthur/.local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "?"\nLINE 1: ?\n        ^\n\n'
2021-07-05 16:13:24,048 (205916/MainThread) pgcli.pgexecute ERROR - sql: '.help', error: SyntaxError('syntax error at or near "."\nLINE 1: .help\n        ^\n')
2021-07-05 16:13:24,049 (205916/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/arthur/.local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/arthur/.local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "."\nLINE 1: .help\n        ^\n\n'
2021-07-05 16:13:26,515 (205916/MainThread) pgcli.pgexecute ERROR - sql: 'help', error: SyntaxError('syntax error at or near "help"\nLINE 1: help\n        ^\n')
2021-07-05 16:13:26,515 (205916/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/arthur/.local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/arthur/.local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "help"\nLINE 1: help\n        ^\n\n'
2021-10-01 03:10:47,242 (377831/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2021-10-01 03:10:47,505 (377831/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/arthur/.local/lib/python3.9/site-packages/pgcli/main.py", line 582, in connect\n    raise e\n  File "/home/arthur/.local/lib/python3.9/site-packages/pgcli/main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/home/arthur/.local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/home/arthur/.local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/home/arthur/.local/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: could not connect to server: No such file or directory\n\tIs the server running locally and accepting\n\tconnections on Unix domain socket "/run/postgresql/.s.PGSQL.5432"?\n\n'
2022-04-03 19:39:51,621 (415580/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-04-03 19:39:51,754 (415580/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.10/site-packages/pgcli/main.py", line 672, in connect\n    raise e\n  File "/usr/lib/python3.10/site-packages/pgcli/main.py", line 659, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 260, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 306, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: could not connect to server: No such file or directory\n\tIs the server running locally and accepting\n\tconnections on Unix domain socket "/run/postgresql/.s.PGSQL.5432"?\n\n'
2022-04-03 19:59:53,982 (419523/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-04-20 11:55:37,564 (720321/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-04-20 11:55:55,614 (720382/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
